### ISSUE TITLE
记录一次排查字体导入不生效问题

### ISSUE THREAD

**Issue by C2015** [C2015/ARTS#4]
## 背景

在一个老项目中需要导入一个新的字体，根据不同的主题来判断是否需要加载。
拿到需求时，我直接复制老代码导入字体的样式，同时在对应的标签引入该字体。这时问题来了，引入的字体没有生效。

```css
    @font-face {
        font-family: 'logic';
        src: url(../font/logic-Regular.woff) format('woff'),
            url(../font/logic-Regular.ttf) format('truetype');
        font-weight: normal;
        font-style: normal;         
    }
    *{
         font-family: logic,Arial,Helvetica,Sans-serif,San Francisco,Microsoft Yahei,SimHei;
    }
```

### 解决问题的过程

**第一个想法**

为啥写的这个字体没生效，连写的后面那个确生效了。难道是我的写法不对，我干掉后面所有的字体试试。干掉之后字体确实变了，我以为是我的字体生效了，其实是走到系统默认的字体微软雅黑去了。ps: 这里发了很多时间纠结为啥删除了就生效上。
其实chrome 可以看到当前生效的字体；查看路径实在控制台: **element => computed** 的最底部。

**第二个想法**

找不到为啥删除就生效，那只好重新写个项目引用字体试试。在新写的项目中引用字体确没有问题。同时发现第一步操作中的删除其他字体并没有生效，而且应用了默认的微软雅黑

**第三个想法**

怀疑项目之前导入字体引用错误，看了下 console 控制台确实是有报字体引用错误。修改 webpack 打包字体的引用路径。

### 总结

- 应该一开始就看控制台有没有报错提示；
- 对字体的导入使用不够熟悉，导致怀疑用错了；
- 对旧项目不要抱有 100% 信任，就算在线上跑了也有可能是错的。
